#' Make nice density plots for feature expression!
#'
#' This functions generates density plots of specified features.
#' @param seurat_object A Seurat object
#' @param genes A gene or vector of genes.
#' @param pal Palette used for shading. Supported options are  "viridis", "flame", "ghost", "mutant", "headlight". You can also supply a custom palette as generated by grDevices::colorRampPalette.
#' @param pal.option Shading option for viridis palette, same as in viridis::scale_fill_viridis.
#' @param pt.size Size of data points.
#' @param stroke Size of border to data points. NOTE: when exportet as PDF, borders can alter the appearance of the plot. To avoid this, export externally as PNG file.
#' @param joint Logical; whether joint expression should be plotted.
#' @param combine Logical; whether plots should be combined or separeate, when genes >1.
#' @param dims Dimensions to plot. By default, plots the first two dimensions.
#' @param axes Logical; whether axes should be shown.
#' @param legend Logical; whether to plot the legend.
#' @param reduction The dimensionality reduction to use.
#' @export
#' @examples
#' KG_density(B_cell_data, genes = "CD27")
KG_density = function(seurat_object,
                           genes,
                           pal = "viridis",
                           pal.option = "viridis",
                           pt.size = 3,
                           stroke = 0.01,
                           joint = FALSE,
                           combine = TRUE,
                           dims = c(1, 2),
                           axes = TRUE,
                           legend = TRUE,
                           reduction = "umap"){

  suppressPackageStartupMessages({
    require(ggplot2)
    require(plotly)
    require(Nebulosa)
    require(Seurat)
    require(SeuratObject)
  })

  print(genes)

  if(joint == TRUE){
    a = Nebulosa::plot_density(seurat_object,
                               features = genes,
                               combine = TRUE,
                               joint = TRUE,
                               dims = dims,
                               reduction = reduction)$data

    title = paste(genes, collapse = "+ ") %>%
      paste0("+")
    dim_names = names(a[1:2])
    names(a)[1:2] = c("dim1", "dim2")
    p = ggplot2::ggplot(data = a %>%
                          plotly::arrange(feature),
                        ggplot2::aes(x = dim1,
                                     y = dim2)) +
      ggplot2::geom_point(ggplot2::aes(fill = feature),
                          size = pt.size,
                          shape = 21,
                          stroke = stroke,
                          color = "black") +
      ggplot2::theme_classic() +
      ggplot2::labs(fill = "Density") +
      ggplot2::guides(fill = ggplot2::guide_colorbar(ticks = FALSE)) +
      ggplot2::ggtitle(paste(title)) +
      ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 18),
                     legend.title = ggplot2::element_text(size = 14),
                     legend.text = ggplot2::element_text(size = 11),
                     axis.title = ggplot2::element_text(size = 14),
                     axis.text = ggplot2::element_text(size = 11)) +
      ggplot2::ylab(dim_names[2]) +
      ggplot2::xlab(dim_names[1])

    if(pal == "viridis"){
      p = p +
        viridis::scale_fill_viridis(option = pal.option)
    } else if(pal == "flame"){
      p = p +
        ggplot2::scale_fill_gradientn(colors = KG::KG_flame_pal(50))
    } else if(pal == "ghost"){
      p = p +
        ggplot2::scale_fill_gradientn(colors = KG::KG_ghost_pal(50))
    } else if (pal == "headlight"){
      p = p +
        ggplot2::scale_fill_gradientn(colors = KG::KG_headlight_pal(50))
    } else if (pal == "mutant"){
      p = p +
        ggplot2::scale_fill_gradientn(colors = KG::KG_mutant_pal(50))
    } else {
      p = p +
        ggplot2::scale_fill_gradientn(colors = pal)
    }

    if(axes == FALSE){
      p = p + Seurat::NoAxes()
    }
    if(legend == FALSE){
      p = p + Seurat::NoLegend()
    }
    return(p)
  } else {

    # Create a list to store plots in
    plot_list = list()
    for (i in genes){
      message(i)
      plot_list[[i]] = local({
        i = i
        a = Nebulosa::plot_density(seurat_object,
                                   i,
                                   combine = combine,
                                   joint = joint,
                                   dims = dims,
                                   reduction = reduction)$data

        dim_names = names(a[1:2])
        names(a)[1:2] = c("dim1", "dim2")

        p1 = ggplot2::ggplot(data = a %>% arrange(feature),
                             ggplot2::aes(x = dim1,
                                          y = dim2)) +
          ggplot2::geom_point(ggplot2::aes(fill = feature),
                              size = pt.size,
                              shape = 21,
                              stroke = stroke,
                              colour = "black") +
          ggplot2::theme_classic() +
          ggplot2::labs(fill = "Density") +
          ggplot2::guides(fill = ggplot2::guide_colorbar(ticks.colour = NA)) +
          ggplot2::ggtitle(paste(i)) +
          theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 18),
                legend.title = ggplot2::element_text(size = 14),
                legend.text = ggplot2::element_text(size = 11),
                axis.title = ggplot2::element_text(size = 14),
                axis.text = ggplot2::element_text(size = 11)) +
          ggplot2::ylab(dim_names[2]) +
          ggplot2::xlab(dim_names[1])

        if(pal == "viridis"){
          p1 = p1 +
            viridis::scale_fill_viridis(option = pal.option)
        } else if(pal == "flame"){
          p1 = p1 +
            ggplot2::scale_fill_gradientn(colors = KG::KG_flame_pal(50))
        } else if(pal == "ghost"){
          p1 = p1 +
            ggplot2::scale_fill_gradientn(colors = KG::KG_ghost_pal(50))
        } else if (pal == "headlight"){
          p1 = p1 +
            ggplot2::scale_fill_gradientn(colors = KG::KG_headlight_pal(50))
        } else if (pal == "mutant"){
          p1 = p1 +
            ggplot2::scale_fill_gradientn(colors = KG::KG_mutant_pal(50))
        } else {
          p1 = p1 +
            ggplot2::scale_fill_gradientn(colors = pal)
        }
        if(axes == FALSE){
          p1 = p1 + NoAxes()
        }
        if(legend == FALSE){
          p1 = p1 + NoLegend()
        }

        # Return the plot object
        return(p1)
      })

    }
    # Arrange plots in a grid
    if(length(genes) > 1){
      do.call(gridExtra::grid.arrange, c(plot_list, ncol = 2))
    } else {
      return(plot_list[[1]])
    }
  }
}
